name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.3.0
  url_launcher: ^6.2.1
  shared_preferences: ^2.2.2
  font_awesome_flutter: ^10.6.0
  carousel_slider: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/lago_villarrica.jpg
    - assets/images/plaza_villarrica.jpg
    - assets/images/villarrica_centro.jpg
    - assets/images/Volcan_Villarrica.webp
  
  # Temporalmente comentado hasta que tengamos las fuentes
  # fonts:
  #   - family: Montserrat
  #     fonts:
  #       - asset: assets/fonts/Montserrat-Regular.ttf
  #       - asset: assets/fonts/Montserrat-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Montserrat-Light.ttf
  #         weight: 300
  #       - asset: assets/fonts/Montserrat-Medium.ttf
  #         weight: 500
